Notification module and Twilio integration
systers/FirstAide-web pull request #254
Opened 2017-07-27 18:05 UTC by fatimarafiqui

2017-07-27 19:57 UTC, fatimarafiqui commented
@prathmeshranaut @MehaKaushik Please review this. Thanks!

2017-07-30 08:52 UTC, MehaKaushik commented on modules/Notification.php
> +                    // the body of the text message you'd like to send
Not a good style of writing comments. Do not use second person reference. Person reading your code is different from person using using your app. 
A more suggestive comment :
"The body of the text message, the logged in user would send to other comrades."

2017-07-30 08:52 UTC, MehaKaushik commented on request/send_notification.php
> +                                via FirstAide web app";
Were these sample messages provided in requirements or mocks ?

2017-07-30 08:52 UTC, MehaKaushik commented on tests/modules/NotificationTest.php
> +     * Description : tests for the full card template content page
Are the comments correct here ?

2017-07-30 08:52 UTC, MehaKaushik commented on tests/modules/NotificationTest.php
> +class NotificationTest extends TestCase
Are these complete set of tests, which you plan to write for this module? or are there any more coming up ?

2017-07-31 07:02 UTC, fatimarafiqui commented on request/send_notification.php
> +                                via FirstAide web app";
@MehaKaushik They were provided in the requirements, and Akanksha used them last year too.

2017-07-31 07:03 UTC, fatimarafiqui commented on tests/modules/NotificationTest.php
> +class NotificationTest extends TestCase
@MehaKaushik According to me, these tests cover all the methods of the notification module. Therefore, their coverage is 100%. Do you have any other test suggestion?

2017-08-01 04:45 UTC, npari commented on modules/User.php
> +    public function getCircleOfTrustNumbers()
Lets add block comments to all methods

2017-08-01 04:51 UTC, npari commented on request/send_notification.php
> +<?php
Lets make this file modular. Very long switch case.

2017-08-01 04:51 UTC, npari commented on request/send_notification.php
> +<?php
Comments need to be added by default for all PRs.

2017-08-01 05:03 UTC, npari requested changes

2017-08-01 05:03 UTC, npari commented on tests/modules/NotificationTest.php
> +    public function testSendSms()
Can we add negative tests as well?

2017-08-01 05:03 UTC, npari commented on tests/modules/NotificationTest.php
> +    public function testSendSms()
Add asserts when invalid message/number is passed in sendSms.

2017-08-01 05:03 UTC, npari commented on tests/modules/NotificationTest.php
> +        $this->assertTrue($sendNotificationRespose['response']);
In addition to checking if there is a response, asserts needs to be added to check if the expected response is received in positive and negative case.

2017-08-01 05:03 UTC, npari commented on tests/modules/NotificationTest.php
> +        $arrayOfTestNumbers = array(
Same comments as above

2017-08-01 05:19 UTC, npari commented on tests/modules/NotificationTest.php
> + * NotificationTest.php is unit test file for Notification module (modules/Notification.php).
You can add a test to see if the account_sid, auth_token and from_number are getting set in the constructor as expected

2017-08-01 05:21 UTC, npari commented on tests/modules/NotificationTest.php
> +class NotificationTest extends TestCase
100% test coverage indicates every branch is tested in a If/else block, every line of code is tested, and every method is tested.

2017-08-01 05:48 UTC, npari commented on modules/User.php
> +    public function getCircleOfTrustNumbers()
Remove commented pieces of code if irrelevant
```
 // Returns country from the given list of countries only
            /*$country_found = in_array($country_found, $active_post_countries) ?
                $country_found :
                'UG';
            */
```

2017-08-01 18:58 UTC, fatimarafiqui commented on tests/modules/NotificationTest.php
> + * NotificationTest.php is unit test file for Notification module (modules/Notification.php).
@npari Twilio is handling this for us. This is not required from our end.

2017-08-02 11:47 UTC, fatimarafiqui commented on tests/modules/NotificationTest.php
> +        $this->assertTrue($sendNotificationRespose['response']);
Done. https://github.com/systers/FirstAide-web/pull/254/commits/a7303aabfeb81f477cff586a72a0d3da7a71cc85

2017-08-02 11:47 UTC, fatimarafiqui commented on tests/modules/NotificationTest.php
> +    public function testSendSms()
Done https://github.com/systers/FirstAide-web/pull/254/commits/a7303aabfeb81f477cff586a72a0d3da7a71cc85

2017-08-02 11:48 UTC, fatimarafiqui commented on tests/modules/NotificationTest.php
> +class NotificationTest extends TestCase
I have added all possible tests.

2017-08-02 11:49 UTC, fatimarafiqui commented on tests/modules/NotificationTest.php
> +class NotificationTest extends TestCase
Added more tests. @npari @MehaKaushik

2017-08-02 11:51 UTC, fatimarafiqui commented on request/send_notification.php
> +<?php
Modularity Done here - https://github.com/systers/FirstAide-web/pull/254/commits/1bc0c1be80f529decd2b1ec00c6be7599c466058
Done here.

2017-08-02 11:55 UTC, fatimarafiqui commented on modules/User.php
> +    public function getCircleOfTrustNumbers()
Done https://github.com/systers/FirstAide-web/pull/254/commits/ef9beed758e1fa026c3fccbadb3e2829e3e7e9d4

2017-08-02 12:33 UTC, fatimarafiqui commented on tests/modules/NotificationTest.php
> +        $arrayOfTestNumbers = array(
Done.

2017-08-02 20:13 UTC, npari approved these changes

2017-08-02 20:13 UTC, merged