Refactoring and Javascript Unit tests for Get Help Now JS file
systers/FirstAide-web pull request #266
Opened 2017-08-21 13:06 UTC by fatimarafiqui

2017-08-21 16:18 UTC, Anjali05 approved these changes

2017-08-21 16:18 UTC, Anjali05 approved these changes

2017-08-21 20:26 UTC, MehaKaushik requested changes

2017-08-21 20:26 UTC, MehaKaushik commented on js/get_help_now.js
> + * showGetHelpActionSection() displays the page section
Mentioning showGetHelpActionSection() was not required.

2017-08-21 20:26 UTC, MehaKaushik commented on js/get_help_now.js
> +		var thisId = $(this).attr('id');
Instead of using "this"Id, why not use "button"Id or "submitButton"id

2017-08-21 20:26 UTC, MehaKaushik commented on tests/jsTests/getHelpNowSpec.js
> +		spyOn($.fn, "fadeOut").and.callFake(function() {
Why are you calling the functions hide and show ? Why are you not calling on-click for contact button ?

2017-08-22 06:01 UTC, fatimarafiqui commented on js/get_help_now.js
> + * showGetHelpActionSection() displays the page section
As discussed in earlier Pull requests and on slack, we are following AirBnB's style guide for comments. Like php comments, we are mentioning function's name here as well. Reference: [Airbnb style guide](https://github.com/airbnb/javascript#comments)

2017-08-22 06:03 UTC, fatimarafiqui commented on js/get_help_now.js
> +		var thisId = $(this).attr('id');
This is a widely used term in JS and Jquery. Just following the coding conventions and naming style, specifying that we are referencing the ID of 'this' particular element.

Reference: [What is this?](http://www.learningjquery.com/2007/08/what-is-this)

2017-08-22 06:09 UTC, fatimarafiqui commented on tests/jsTests/getHelpNowSpec.js
> +		spyOn($.fn, "fadeOut").and.callFake(function() {
These are mock function calls for supporting jquery's fadeOut and fadeIn. Technically, fadeOut hides and fadeIn shows the element with a delay. I have mocked these function calls to test these functionalities. show and hide functions are functions of jquery.

Reference: [Intro to jasmine](https://jasmine.github.io/2.0/introduction.html) | [hide](http://api.jquery.com/hide/) | [show](http://api.jquery.com/show/)

2017-08-23 03:59 UTC, MehaKaushik approved these changes

2017-08-23 03:59 UTC, MehaKaushik commented on js/get_help_now.js
> +		var thisId = $(this).attr('id');
Great !!

2017-08-23 06:37 UTC, merged